name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build the application
        run: yarn build

      - name: Start server
        run: npm start &

      - name: Wait for server to be ready
        run: |
          for i in $(seq 1 30); do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server..."
            sleep 10
          done
          echo "Server did not start in time!"
          exit 1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: 'cypress/e2e/**/*.spec.js' # Adjust if needed
