name: Run Cypress and Notify Slack

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run test || echo "CYPRESS_FAILED=true" >> $GITHUB_ENV

      - name: Upload MochaAwesome Report (if failed)
        if: env.CYPRESS_FAILED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/results/mochawesome.html

      - name: Send Slack Notification (if failed)
        if: env.CYPRESS_FAILED == 'true'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "#test-gh-notif"
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          filename: "mochawesome.html"
          file-path: "path/to/mochawesome.html"
          initial-comment: "🚨 Test run failed! Here's the report."

      - name: Send Success Message (if passed)
        if: env.CYPRESS_FAILED != 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          text: "✅ All Cypress tests passed successfully!"
