name: Run Cypress and Send Report to Slack

on: [push, pull_request]

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Start the server
        run: npm start &
      
      - name: Wait for server to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server..."
            sleep 5
          done
          echo "Server did not start in time!"
          exit 1

      - name: Run Cypress Tests
        run: npx cypress run --reporter mochawesome || echo "CYPRESS_FAILED=true" >> $GITHUB_ENV

      - name: Upload MochaAwesome Report (if failed)
        if: env.CYPRESS_FAILED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/results/

      - name: Retrieve Artifact URL
        if: env.CYPRESS_FAILED == 'true'
        id: get_artifact_url
        run: |
          # Set the GH_TOKEN environment variable for GitHub CLI
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          
          # Retrieve the artifact ID using GitHub CLI
          ARTIFACT_ID=$(gh run view $GITHUB_RUN_ID --json artifacts -q ".artifacts[0].id")
          
          # Construct the artifact URL
          ARTIFACT_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${ARTIFACT_ID}"
          
          # Output the URL to the GitHub environment
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV
          
      - name: Send Slack Notification with Artifact Link (if failed)
        if: env.CYPRESS_FAILED == 'true'
        run: |
          curl -X POST "https://slack.com/api/chat.postMessage" \
          -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "channel": "#test-gh-notif",
                "text": "🚨 Test run failed! Here is the Report: <${{ env.ARTIFACT_URL }}|Download Report>"
              }'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send Success Message (if passed)
        if: env.CYPRESS_FAILED != 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: "Predictor E2E test"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "✅ All Cypress tests passed successfully!"
          MSG_MINIMAL: "true"
